POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Alan Turing",
  "number": "23-06-1912"
}

###

# Number missing, should return 400
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Linus Torvalds"
}

###

# Name missing, should return 400
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number": "1337"
}

###

# Duplicate name, should return 400
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Alan Turing",
  "number": "23-06-1912"
}
